#!/bin/sh

echo "bootstrap (libwardenc): creating automake config directories"
mkdir -p config/m4 || exit 1

echo "bootstrap (libwardenc): generating autotools files"
autoreconf --verbose --force --install || exit 1

echo "bootstrap (libwardenc): success"
